### ISSUE TITLE
12F: Build, release, run

### ISSUE THREAD

**Issue by anreinha** [cloudy-sentiment-analysis/CloudyMcCloudface#15]

**Comment by markusheilig** [comment]
- see: https://12factor.net/build-release-run
- build stage:
    - fetch dependencies (npm)
    - no compile step required for javascript/node-app
- release stage:
   - bundle output from build stage (our node-services+dependencies) as well as configuration
- run stage:
    - run the app in the execution environment 'aws' (triggered by travis)
