### ISSUE TITLE
12F: Disposability

### ISSUE THREAD

**Issue by anreinha** [cloudy-sentiment-analysis/CloudyMcCloudface#19]

**Comment by markusheilig** [comment]
- see: https://12factor.net/disposability
- node-services can be started or stopped at a moment’s notice using npm
- using node, the microservices have a minimum of startup time compared to other technologies (e.g. java lasagne enterprise stack)
- shut down gracefully + robust against sudden death: redis-keys expire -> other services start a battle for tenants
