### ISSUE TITLE
12F: Dev/prod parity

### ISSUE THREAD

**Issue by anreinha** [cloudy-sentiment-analysis/CloudyMcCloudface#20]

**Comment by markusheilig** [comment]
- see: https://12factor.net/dev-prod-parity
- keeping the gap between development and production small
  - time gap: write code and have it deployed hours or even just minutes later (auto deploy using travis)
  - personnel gap: developers who wrote code are closely involved in deploying it and watching its behavior in production (developers configure travis)
  - tools gap small: using docker+localstack, we have the same test/dev system as aws-prod system
