### ISSUE TITLE
dynamo - record tweets

### ISSUE THREAD

**Issue by markusheilig** [cloudy-sentiment-analysis/CloudyMcCloudface#8]

**Comment by markusheilig** [comment]
@alvilgau could you please create a rest api for:
  - record tweets (keywords + time range) -> only store specific tweets (depending on keyword) for a given time 
  - query recorded tweets

thx :-)

**Comment by alvilgau** [comment]
query recorded tweets is implemented now.

example call:
http://localhost:3010/tweets/tenantId/keyword?begin=1497089445404&end=1497091981727
